// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.Payments.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PaymentServiceFeature : object, global::Xunit.IClassFixture<PaymentServiceFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "PaymentService", "  Como parte do sistema de pagamentos FCG\r\n  Quero processar pagamentos de pedido" +
                "s de jogos\r\n  Para garantir que o fluxo de compra seja registrado corretamente", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentService.feature"
#line hidden
        
        public PaymentServiceFeature(PaymentServiceFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("BDD/Features/PaymentService.feature", "Feature: PaymentService\n  Como parte do sistema de pagamentos FCG\n  Quero process" +
                    "ar pagamentos de pedidos de jogos\n  Para garantir que o fluxo de compra seja reg" +
                    "istrado corretamente\n\n  Scenario: Processar pagamento aprovado\n    Given um pedi" +
                    "do válido com preço de 59.90\n    When o serviço processa o pagamento com resulta" +
                    "do aprovado\n    Then o Payment deve ter status \"Approved\"\n    And o Amount do Pa" +
                    "yment deve ser 59.90\n    And o Reason do Payment deve ser nulo\n\n  Scenario: Proc" +
                    "essar pagamento rejeitado\n    Given um pedido válido com preço de 120.00\n    Whe" +
                    "n o serviço processa o pagamento com resultado rejeitado\n    Then o Payment deve" +
                    " ter status \"Rejected\"\n    And o Reason do Payment deve ser \"Insufficient funds " +
                    "(simulated)\"\n\n  Scenario: Preservar OrderId no Payment\n    Given um pedido com O" +
                    "rderId específico\n    When o serviço processa o pagamento com resultado aprovado" +
                    "\n    Then o Payment deve preservar o OrderId do pedido\n\n  Scenario: Preservar Us" +
                    "erId no Payment\n    Given um pedido com UserId específico\n    When o serviço pro" +
                    "cessa o pagamento com resultado aprovado\n    Then o Payment deve preservar o Use" +
                    "rId do pedido\n\n  Scenario: Preservar GameId no Payment\n    Given um pedido com G" +
                    "ameId específico\n    When o serviço processa o pagamento com resultado aprovado\n" +
                    "    Then o Payment deve preservar o GameId do pedido\n\n  Scenario: Preservar Game" +
                    "Title no Payment\n    Given um pedido com GameTitle \"Elden Ring\"\n    When o servi" +
                    "ço processa o pagamento com resultado aprovado\n    Then o Payment deve ter GameT" +
                    "itle \"Elden Ring\"\n\n  Scenario: Preservar UserEmail no Payment\n    Given um pedid" +
                    "o com UserEmail \"jogador@fcg.com\"\n    When o serviço processa o pagamento com re" +
                    "sultado aprovado\n    Then o Payment deve ter UserEmail \"jogador@fcg.com\"\n\n  Scen" +
                    "ario: Payment deve ter Id único\n    Given um pedido válido com preço de 30.00\n  " +
                    "  When o serviço processa o pagamento com resultado aprovado\n    Then o Payment " +
                    "deve ter um Id não vazio\n\n  Scenario: Repositório deve ser chamado ao processar " +
                    "pagamento\n    Given um pedido válido com preço de 45.00\n    When o serviço proce" +
                    "ssa o pagamento com resultado aprovado\n    Then o repositório deve ter persistid" +
                    "o o Payment exatamente uma vez\n\n  Scenario: ProcessedAt deve ser próximo do mome" +
                    "nto atual\n    Given um pedido válido com preço de 75.00\n    When o serviço proce" +
                    "ssa o pagamento com resultado aprovado\n    Then o ProcessedAt do Payment deve se" +
                    "r próximo do momento atual\n\n  Scenario: Dois pagamentos devem ter Ids diferentes" +
                    "\n    Given dois pedidos válidos distintos\n    When o serviço processa ambos os p" +
                    "agamentos com resultado aprovado\n    Then os dois Payments devem ter Ids diferen" +
                    "tes\n\n  Scenario: Strategy de aprovação deve ser consultada ao processar\n    Give" +
                    "n um pedido válido com preço de 99.90\n    When o serviço processa o pagamento co" +
                    "m resultado aprovado\n    Then a strategy de aprovação deve ter sido consultada e" +
                    "xatamente uma vez\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("BDD/Features/PaymentService.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "PaymentService", "  Como parte do sistema de pagamentos FCG\r\n  Quero processar pagamentos de pedido" +
                        "s de jogos\r\n  Para garantir que o fluxo de compra seja registrado corretamente", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Processar pagamento aprovado", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 59.90", null, null, "b242bdda572a1f548894b7bd77a44d7c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "545abd77bda9e250924bb32660a2a3b8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter status \"Approved\"", null, null, "2c1952bcf0f123578aead192ae691d3d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o Amount do Payment deve ser 59.90", null, null, "23b2b5bb3789a955ba314301f85f7092"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o Reason do Payment deve ser nulo", null, null, "2bcd0bb8f5dd6e5bb8cb872bd39468aa")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "94245650d0411e5aaab6962f8d51ba36")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Processar pagamento rejeitado", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 120.00", null, null, "950daa5fb408dc508ff73e401bc2265d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado rejeitado", null, null, "9f11c3c435ecac51b12453c70b1c1e7c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter status \"Rejected\"", null, null, "1d7c7ab57150d258bcd9e13065039ee2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o Reason do Payment deve ser \"Insufficient funds (simulated)\"", null, null, "40ce08a7f277065bbe95135b052cbe4c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e29d78aff1b8875d9e6b2931cacb3043")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar OrderId no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com OrderId específico", null, null, "42d03af6ca1ec251a986824628d38968"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "698059aecdbe6658b1e1c4fc4f8edc59"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve preservar o OrderId do pedido", null, null, "6a8dddd170e21352ac1a6467e0c1b073")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ca812daa3bad0d569afc44c397ca3b18")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar UserId no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com UserId específico", null, null, "039fd0829fb2d35bab6e9be4756b87cd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "0876a90da5097051a8e99986cd9fe0f5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve preservar o UserId do pedido", null, null, "f9057bab74f6425c81f660fc5bb40793")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d76ae238a266655683bba43d797a887a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar GameId no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com GameId específico", null, null, "fa4c0b98122f5b51ae6f93ac2c242c1f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "c641d5ac310d9250977bb94db2b5ffe3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve preservar o GameId do pedido", null, null, "318e8ecabccb6e55a601f06bca1becab")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "333470992147fc5f9e187473ecf50652")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar GameTitle no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com GameTitle \"Elden Ring\"", null, null, "7a00f9bb7f452153854071c71f5daf5d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "33e89fd02a95ac56a54be104a8e0fc62"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter GameTitle \"Elden Ring\"", null, null, "1a011f4f91c052518380077f0201a687")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a534fd636b609952977745c5bb6b99c7")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar UserEmail no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com UserEmail \"jogador@fcg.com\"", null, null, "4281f909a2bc625ba029992771951235"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "efe4c6a681e6275ba307fba0f979c48f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter UserEmail \"jogador@fcg.com\"", null, null, "c207048fb8cbd35db88be727920a46ae")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "853766c6ea753f5686b3c65d28a537da")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Payment deve ter Id único", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 30.00", null, null, "872f16c5455be15d8e3b5c847614ffd1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "d14981451d22625595c47b44745881e7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter um Id não vazio", null, null, "57fe798b17e4b15499804674a3023198")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a046086743112e5492fa089b9202fa50")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Repositório deve ser chamado ao processar pagamento", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 45.00", null, null, "b28538e73f2fef568f81ccddd6572126"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "79c6beebddc970558d98791d545ccde2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o repositório deve ter persistido o Payment exatamente uma vez", null, null, "ee86847ca409045aa79aecbf8eb2c84f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "131125cbe9e27e50941a768a1c44d0b9")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "ProcessedAt deve ser próximo do momento atual", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 75.00", null, null, "6ab8c791286553519fa5e3d7a183a267"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "7c1dbf30bbbd0e579235d5c2f75e0351"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o ProcessedAt do Payment deve ser próximo do momento atual", null, null, "0b955aaf9e416354a265af0baff5dec3")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "194a07d5b24aa4589857428404e927b2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Dois pagamentos devem ter Ids diferentes", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "dois pedidos válidos distintos", null, null, "ba595ed30969e55ca829285b1871d00d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa ambos os pagamentos com resultado aprovado", null, null, "52d5a19251f3dd5eb2de0b8724666f6e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "os dois Payments devem ter Ids diferentes", null, null, "471f9f5008f38452abd4aba26f3e6723")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d06d0486ec683f5f96bf4fa54d65b84d")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Strategy de aprovação deve ser consultada ao processar", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(65, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 99.90", null, null, "d9d76b533b48c65897b433549138b81a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "97d5e96420933859b677d7c599d44bc6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a strategy de aprovação deve ter sido consultada exatamente uma vez", null, null, "6b5e405e42fac85390bf9c99198f1807")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0c6d00e52a73af549521354760a07b66"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("086a3dffc79246529bbe06764cb7c8e6", "BDD/Features/PaymentService.feature", "Processar pagamento aprovado", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b242bdda572a1f548894b7bd77a44d7c"}), "d5e276fedcbbdb5c841f0e2b3d2bc1d8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 59.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "545abd77bda9e250924bb32660a2a3b8"}), "9a2c19668c1e175e9adb4de93f64647b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2c1952bcf0f123578aead192ae691d3d"}), "7657474dd8fcf4528dc35f0a61123b83", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter status \"Approved\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "23b2b5bb3789a955ba314301f85f7092"}), "803cc3a12eda6453aca951c5939011ee", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Amount do Payment deve ser 59.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2bcd0bb8f5dd6e5bb8cb872bd39468aa"}), "9e36e07b8a08765291e71f10fd922fff", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Reason do Payment deve ser nulo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "94245650d0411e5aaab6962f8d51ba36"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a4388ee1a04aa653b20f50ae8edfe968", "BDD/Features/PaymentService.feature", "Processar pagamento rejeitado", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "950daa5fb408dc508ff73e401bc2265d"}), "97f46bc07d2e5b518a41120d605150a4", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 120.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9f11c3c435ecac51b12453c70b1c1e7c"}), "fb19ea436be6275dbead1e8a7c1e34c7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado rejeitado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1d7c7ab57150d258bcd9e13065039ee2"}), "89cfe9daec9b515ab5f4293e59656de3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter status \"Rejected\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "40ce08a7f277065bbe95135b052cbe4c"}), "d99151e7f08320539baddee0ae6f68cc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Reason do Payment deve ser \"Insufficient funds (simulated)\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e29d78aff1b8875d9e6b2931cacb3043"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("48135d1c9893a25292151bf3475366cd", "BDD/Features/PaymentService.feature", "Preservar OrderId no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42d03af6ca1ec251a986824628d38968"}), "76503e334f11f55aaf9124f0768b9dab", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com OrderId específico"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "698059aecdbe6658b1e1c4fc4f8edc59"}), "ec52efbd79142d5396a356aa92ecea16", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6a8dddd170e21352ac1a6467e0c1b073"}), "2db6b739becee4579e9dcfe5e6cb8409", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve preservar o OrderId do pedido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "ca812daa3bad0d569afc44c397ca3b18"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ce6efc1759d4a65fbb6be4e2dc40656f", "BDD/Features/PaymentService.feature", "Preservar UserId no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "039fd0829fb2d35bab6e9be4756b87cd"}), "31f143c845eb485caa2e747aa2f879ab", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com UserId específico"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0876a90da5097051a8e99986cd9fe0f5"}), "ccf35ada51126c5ab4488e4145f4e320", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f9057bab74f6425c81f660fc5bb40793"}), "cf88845693df3d5283d5454336022098", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve preservar o UserId do pedido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "d76ae238a266655683bba43d797a887a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("90746e168061b85281d3157a83f1ae9e", "BDD/Features/PaymentService.feature", "Preservar GameId no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fa4c0b98122f5b51ae6f93ac2c242c1f"}), "eda4828b1161fd56bac410a1896c4057", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com GameId específico"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c641d5ac310d9250977bb94db2b5ffe3"}), "b731abd882f7c852a12028d509678d96", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "318e8ecabccb6e55a601f06bca1becab"}), "90d437513ccf8358bdb819143b1b234f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve preservar o GameId do pedido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "333470992147fc5f9e187473ecf50652"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ac916bcd49999c588bc8b014392fc81d", "BDD/Features/PaymentService.feature", "Preservar GameTitle no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7a00f9bb7f452153854071c71f5daf5d"}), "5c5b9af01224205aaab9231b85b48dd0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com GameTitle \"Elden Ring\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "33e89fd02a95ac56a54be104a8e0fc62"}), "a46959c404245b55bc6a862e21c943b4", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1a011f4f91c052518380077f0201a687"}), "0d99bd2d8f44c15cbf64a8e540b86d8f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter GameTitle \"Elden Ring\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "a534fd636b609952977745c5bb6b99c7"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("543a953c27614052982682e27f63ea35", "BDD/Features/PaymentService.feature", "Preservar UserEmail no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4281f909a2bc625ba029992771951235"}), "b167395bbf216d5e92af2f8a9d87e463", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com UserEmail \"jogador@fcg.com\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efe4c6a681e6275ba307fba0f979c48f"}), "98aab3bb3bcf1d5aaafb20c394919738", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c207048fb8cbd35db88be727920a46ae"}), "c661e5ada12189518dd11ac6b220c7b8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter UserEmail \"jogador@fcg.com\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "853766c6ea753f5686b3c65d28a537da"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("c8e16b6e9fefc555b5bbf60241870b6a", "BDD/Features/PaymentService.feature", "Payment deve ter Id único", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "872f16c5455be15d8e3b5c847614ffd1"}), "4a24317b80f2eb54930de5b9d8445301", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 30.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d14981451d22625595c47b44745881e7"}), "9e3be3bf6e956f56a5bb9c58efdb3839", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "57fe798b17e4b15499804674a3023198"}), "5da5dc3ad3b20f53bb0c9b7caf91f2f6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter um Id não vazio")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "a046086743112e5492fa089b9202fa50"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("702df57042918c5f84744dca04687075", "BDD/Features/PaymentService.feature", "Repositório deve ser chamado ao processar pagamento", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b28538e73f2fef568f81ccddd6572126"}), "e5d336639131d85584d7ce48c4bdf160", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 45.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "79c6beebddc970558d98791d545ccde2"}), "0221f113258e6c5c893ebb41cc3f9038", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ee86847ca409045aa79aecbf8eb2c84f"}), "f8be2c90ec0c2f50a913857be084d259", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o repositório deve ter persistido o Payment exatamente uma vez")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "131125cbe9e27e50941a768a1c44d0b9"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3d980c62574bac52b563d019cc9e7b64", "BDD/Features/PaymentService.feature", "ProcessedAt deve ser próximo do momento atual", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6ab8c791286553519fa5e3d7a183a267"}), "7016a34a03ddb851b8ddf3f86f8af92a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 75.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7c1dbf30bbbd0e579235d5c2f75e0351"}), "201f3252ede45d58b7131b213b5744d9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0b955aaf9e416354a265af0baff5dec3"}), "fe266212dd8fe054946ea9e4044295cc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o ProcessedAt do Payment deve ser próximo do momento atual")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "194a07d5b24aa4589857428404e927b2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ef8a5be66f27c4549052e801dff03f8a", "BDD/Features/PaymentService.feature", "Dois pagamentos devem ter Ids diferentes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ba595ed30969e55ca829285b1871d00d"}), "5024be7e68cde8528df33dd069a91ad2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "dois pedidos válidos distintos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "52d5a19251f3dd5eb2de0b8724666f6e"}), "e488805ea5e2be5daaa3e0ac3fb8106e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa ambos os pagamentos com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "471f9f5008f38452abd4aba26f3e6723"}), "4576fd51e395a75bb25564d60aadcf6d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "os dois Payments devem ter Ids diferentes")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "d06d0486ec683f5f96bf4fa54d65b84d"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("60656633699b205cbc8c55450b01d777", "BDD/Features/PaymentService.feature", "Strategy de aprovação deve ser consultada ao processar", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d9d76b533b48c65897b433549138b81a"}), "794072ed0034e850a96f59875856187b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 99.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "97d5e96420933859b677d7c599d44bc6"}), "af0582d63eb3c65485516f4e96966013", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6b5e405e42fac85390bf9c99198f1807"}), "408648a556260a5f85259bf865a17268", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a strategy de aprovação deve ter sido consultada exatamente uma vez")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0c6d00e52a73af549521354760a07b66"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PaymentServiceFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PaymentServiceFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PaymentServiceFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Processar pagamento aprovado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Processar pagamento aprovado")]
        public async global::System.Threading.Tasks.Task ProcessarPagamentoAprovado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Processar pagamento aprovado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("um pedido válido com preço de 59.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("o Payment deve ter status \"Approved\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("o Amount do Payment deve ser 59.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("o Reason do Payment deve ser nulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Processar pagamento rejeitado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Processar pagamento rejeitado")]
        public async global::System.Threading.Tasks.Task ProcessarPagamentoRejeitado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Processar pagamento rejeitado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("um pedido válido com preço de 120.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado rejeitado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("o Payment deve ter status \"Rejected\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.AndAsync("o Reason do Payment deve ser \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar OrderId no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar OrderId no Payment")]
        public async global::System.Threading.Tasks.Task PreservarOrderIdNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar OrderId no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("um pedido com OrderId específico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("o Payment deve preservar o OrderId do pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar UserId no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar UserId no Payment")]
        public async global::System.Threading.Tasks.Task PreservarUserIdNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar UserId no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("um pedido com UserId específico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("o Payment deve preservar o UserId do pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar GameId no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar GameId no Payment")]
        public async global::System.Threading.Tasks.Task PreservarGameIdNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar GameId no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("um pedido com GameId específico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("o Payment deve preservar o GameId do pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar GameTitle no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar GameTitle no Payment")]
        public async global::System.Threading.Tasks.Task PreservarGameTitleNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar GameTitle no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("um pedido com GameTitle \"Elden Ring\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("o Payment deve ter GameTitle \"Elden Ring\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar UserEmail no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar UserEmail no Payment")]
        public async global::System.Threading.Tasks.Task PreservarUserEmailNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar UserEmail no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
    await testRunner.GivenAsync("um pedido com UserEmail \"jogador@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("o Payment deve ter UserEmail \"jogador@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Payment deve ter Id único")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Payment deve ter Id único")]
        public async global::System.Threading.Tasks.Task PaymentDeveTerIdUnico()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Payment deve ter Id único", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("um pedido válido com preço de 30.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("o Payment deve ter um Id não vazio", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Repositório deve ser chamado ao processar pagamento")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Repositório deve ser chamado ao processar pagamento")]
        public async global::System.Threading.Tasks.Task RepositorioDeveSerChamadoAoProcessarPagamento()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Repositório deve ser chamado ao processar pagamento", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("um pedido válido com preço de 45.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("o repositório deve ter persistido o Payment exatamente uma vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ProcessedAt deve ser próximo do momento atual")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "ProcessedAt deve ser próximo do momento atual")]
        public async global::System.Threading.Tasks.Task ProcessedAtDeveSerProximoDoMomentoAtual()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessedAt deve ser próximo do momento atual", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("um pedido válido com preço de 75.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("o ProcessedAt do Payment deve ser próximo do momento atual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Dois pagamentos devem ter Ids diferentes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Dois pagamentos devem ter Ids diferentes")]
        public async global::System.Threading.Tasks.Task DoisPagamentosDevemTerIdsDiferentes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dois pagamentos devem ter Ids diferentes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 60
    await testRunner.GivenAsync("dois pedidos válidos distintos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.WhenAsync("o serviço processa ambos os pagamentos com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
    await testRunner.ThenAsync("os dois Payments devem ter Ids diferentes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Strategy de aprovação deve ser consultada ao processar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Strategy de aprovação deve ser consultada ao processar")]
        public async global::System.Threading.Tasks.Task StrategyDeAprovacaoDeveSerConsultadaAoProcessar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Strategy de aprovação deve ser consultada ao processar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 64
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.GivenAsync("um pedido válido com preço de 99.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("a strategy de aprovação deve ter sido consultada exatamente uma vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PaymentServiceFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PaymentServiceFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
