// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.Payments.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PaymentServiceFeature : object, global::Xunit.IClassFixture<PaymentServiceFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "PaymentService", "  Como parte do sistema de pagamentos FCG\r\n  Quero processar pagamentos de pedido" +
                "s de jogos\r\n  Para garantir que o fluxo de compra seja registrado corretamente", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentService.feature"
#line hidden
        
        public PaymentServiceFeature(PaymentServiceFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("BDD/Features/PaymentService.feature", "Feature: PaymentService\r\n  Como parte do sistema de pagamentos FCG\r\n  Quero proce" +
                    "ssar pagamentos de pedidos de jogos\r\n  Para garantir que o fluxo de compra seja " +
                    "registrado corretamente\r\n\r\n  Scenario: Processar pagamento aprovado\r\n    Given u" +
                    "m pedido válido com preço de 59.90\r\n    When o serviço processa o pagamento com " +
                    "resultado aprovado\r\n    Then o Payment deve ter status \"Approved\"\r\n    And o Amo" +
                    "unt do Payment deve ser 59.90\r\n    And o Reason do Payment deve ser nulo\r\n\r\n  Sc" +
                    "enario: Processar pagamento rejeitado\r\n    Given um pedido válido com preço de 1" +
                    "20.00\r\n    When o serviço processa o pagamento com resultado rejeitado\r\n    Then" +
                    " o Payment deve ter status \"Rejected\"\r\n    And o Reason do Payment deve ser \"Ins" +
                    "ufficient funds (simulated)\"\r\n\r\n  Scenario: Preservar OrderId no Payment\r\n    Gi" +
                    "ven um pedido com OrderId específico\r\n    When o serviço processa o pagamento co" +
                    "m resultado aprovado\r\n    Then o Payment deve preservar o OrderId do pedido\r\n\r\n " +
                    " Scenario: Preservar UserId no Payment\r\n    Given um pedido com UserId específic" +
                    "o\r\n    When o serviço processa o pagamento com resultado aprovado\r\n    Then o Pa" +
                    "yment deve preservar o UserId do pedido\r\n\r\n  Scenario: Preservar GameId no Payme" +
                    "nt\r\n    Given um pedido com GameId específico\r\n    When o serviço processa o pag" +
                    "amento com resultado aprovado\r\n    Then o Payment deve preservar o GameId do ped" +
                    "ido\r\n\r\n  Scenario: Preservar GameTitle no Payment\r\n    Given um pedido com GameT" +
                    "itle \"Elden Ring\"\r\n    When o serviço processa o pagamento com resultado aprovad" +
                    "o\r\n    Then o Payment deve ter GameTitle \"Elden Ring\"\r\n\r\n  Scenario: Preservar U" +
                    "serEmail no Payment\r\n    Given um pedido com UserEmail \"jogador@fcg.com\"\r\n    Wh" +
                    "en o serviço processa o pagamento com resultado aprovado\r\n    Then o Payment dev" +
                    "e ter UserEmail \"jogador@fcg.com\"\r\n\r\n  Scenario: Payment deve ter Id único\r\n    " +
                    "Given um pedido válido com preço de 30.00\r\n    When o serviço processa o pagamen" +
                    "to com resultado aprovado\r\n    Then o Payment deve ter um Id não vazio\r\n\r\n  Scen" +
                    "ario: Repositório deve ser chamado ao processar pagamento\r\n    Given um pedido v" +
                    "álido com preço de 45.00\r\n    When o serviço processa o pagamento com resultado " +
                    "aprovado\r\n    Then o repositório deve ter persistido o Payment exatamente uma ve" +
                    "z\r\n\r\n  Scenario: ProcessedAt deve ser próximo do momento atual\r\n    Given um ped" +
                    "ido válido com preço de 75.00\r\n    When o serviço processa o pagamento com resul" +
                    "tado aprovado\r\n    Then o ProcessedAt do Payment deve ser próximo do momento atu" +
                    "al\r\n\r\n  Scenario: Dois pagamentos devem ter Ids diferentes\r\n    Given dois pedid" +
                    "os válidos distintos\r\n    When o serviço processa ambos os pagamentos com result" +
                    "ado aprovado\r\n    Then os dois Payments devem ter Ids diferentes\r\n\r\n  Scenario: " +
                    "Strategy de aprovação deve ser consultada ao processar\r\n    Given um pedido váli" +
                    "do com preço de 99.90\r\n    When o serviço processa o pagamento com resultado apr" +
                    "ovado\r\n    Then a strategy de aprovação deve ter sido consultada exatamente uma " +
                    "vez\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("BDD/Features/PaymentService.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "PaymentService", "  Como parte do sistema de pagamentos FCG\r\n  Quero processar pagamentos de pedido" +
                        "s de jogos\r\n  Para garantir que o fluxo de compra seja registrado corretamente", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Processar pagamento aprovado", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 59.90", null, null, "0fe4dfe968592455b3ffca082b467a26"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "789156fce275475ba0334847d2f18e4b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter status \"Approved\"", null, null, "fda9c6d5a356b454b11a313a5ef5b726"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o Amount do Payment deve ser 59.90", null, null, "608e366e8d1a845bb4cdbbd55e3daf3e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o Reason do Payment deve ser nulo", null, null, "8846715e4682da588d4dd9f0f131e322")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "605d5ffc6b567b5cbc88c81db60db9f3")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Processar pagamento rejeitado", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 120.00", null, null, "20e24e3f12a50d5d97788cd3ac7c0f45"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado rejeitado", null, null, "820aac3fbbefd55989df241918cb4c80"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter status \"Rejected\"", null, null, "9065ef6b4fc10a579bada2c3dfdc877c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "o Reason do Payment deve ser \"Insufficient funds (simulated)\"", null, null, "3575b4b7df58d2538cf5ae62fa4aa80b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "7514ae10955e625583b3ccf26afc00be")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar OrderId no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com OrderId específico", null, null, "3d4a697f2f062c5992735be32e03ea38"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "b67df8ba25ce585c849bc8ec0e238aa5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve preservar o OrderId do pedido", null, null, "f02ba36b9ee421538109a923c43deb03")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "08f6a4f012c17d56827f823fbd0d2c72")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar UserId no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com UserId específico", null, null, "c3cbf44e936b045fa7140156a87768d0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "635ba07de4e8ad55a4a34f03d363031c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve preservar o UserId do pedido", null, null, "3274491d79ceb65087513d7e7a75184c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "33e62c3727d3d1558e0a661b508464ae")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar GameId no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com GameId específico", null, null, "5a3fb50f08e21553b5878914313861b4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "e851ff2d35cd665e9664dbb79df8fba3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve preservar o GameId do pedido", null, null, "4ebdd2155e4cf15daf8c4230ac327daa")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b3af739ca46b3552b21a07439ef9be44")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar GameTitle no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com GameTitle \"Elden Ring\"", null, null, "b6ce1e3de2f72c59b55b1a1b0d8d1702"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "27569a2e88cdd05b891393983dcfc9b9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter GameTitle \"Elden Ring\"", null, null, "2ee7c14b49bac35fba06bd5c326b9f5d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2335ed5b93b9de51989da3ec2b7a3f8b")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Preservar UserEmail no Payment", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido com UserEmail \"jogador@fcg.com\"", null, null, "e40e8458ea8aa7588ed6896354be29a4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "a626b6099929445fa861c676763d8903"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter UserEmail \"jogador@fcg.com\"", null, null, "5a3b736a821c005fa2e00dc79177d8e2")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "006a006119201a5fa64fd3510b38558c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Payment deve ter Id único", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 30.00", null, null, "f54778d40f517c5898bc8fc22366cf42"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "5daa6ee666dc435b9778e86fde36c0d9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o Payment deve ter um Id não vazio", null, null, "988642afec457855b6e5c413b2f7cd2e")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d147b1ea10d7e85a84b807040db8d7b2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Repositório deve ser chamado ao processar pagamento", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 45.00", null, null, "7307c48d123eed57ad62fb780295e8fd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "9d9e60731295505dbf7bda5c560583c7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o repositório deve ter persistido o Payment exatamente uma vez", null, null, "7e491131a33e445c9d3245a3df30b1c3")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "8bc12b31d39ff7589914347fb6bf561b")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "ProcessedAt deve ser próximo do momento atual", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 75.00", null, null, "0adb71f88c148c5bb529b5d091ea9914"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "3c879c9af3c4c056b7db539bc8180d13"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "o ProcessedAt do Payment deve ser próximo do momento atual", null, null, "17b4a4e5d412b35ca06447d753f90d8f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b90f55266e6c9d558c2d0ab5f4b96672")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Dois pagamentos devem ter Ids diferentes", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "dois pedidos válidos distintos", null, null, "3c51bce16d703053ad2ffcdf24cd9e24"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa ambos os pagamentos com resultado aprovado", null, null, "62236919f170195bbe4e720e209e85f1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "os dois Payments devem ter Ids diferentes", null, null, "b7b1289b77d10552b912f01b77b5c868")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "811380c1a3bf8f58b4e12c4a08623fb7")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Strategy de aprovação deve ser consultada ao processar", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(65, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "um pedido válido com preço de 99.90", null, null, "7e34e1b4e3ac8d55b7ad5102ae8dc888"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "o serviço processa o pagamento com resultado aprovado", null, null, "e3a13b6d9c34745d94b4f12b5ac49051"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a strategy de aprovação deve ter sido consultada exatamente uma vez", null, null, "8b249516aa460456b468431608739ca3")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "9f6dfba3aa1a2654bce9dd6b9512fcd6"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("b21f0bad8da7fc5bb85f4191743715c2", "BDD/Features/PaymentService.feature", "Processar pagamento aprovado", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0fe4dfe968592455b3ffca082b467a26"}), "c29b38a7efe87f5aa86edca5d1178fde", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 59.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "789156fce275475ba0334847d2f18e4b"}), "80bc6a2e105ce05fa608e9ad9bf05681", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fda9c6d5a356b454b11a313a5ef5b726"}), "08049100381cf95a86a638ec0abc64e7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter status \"Approved\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "608e366e8d1a845bb4cdbbd55e3daf3e"}), "1ac462d6831c9658825c0154fd5a2e9f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Amount do Payment deve ser 59.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8846715e4682da588d4dd9f0f131e322"}), "51c116c30697bc5ab28df1efe1cccb89", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Reason do Payment deve ser nulo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "605d5ffc6b567b5cbc88c81db60db9f3"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6fc6728adc90aa59b2a3ed86bce74437", "BDD/Features/PaymentService.feature", "Processar pagamento rejeitado", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "20e24e3f12a50d5d97788cd3ac7c0f45"}), "00fc83173e5f9950bb5509c2b985ab1c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 120.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "820aac3fbbefd55989df241918cb4c80"}), "223b2d0cbd0513568b969f0419dd805c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado rejeitado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9065ef6b4fc10a579bada2c3dfdc877c"}), "e7d97112d25b5e59a1e9fbe29c0c91aa", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter status \"Rejected\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3575b4b7df58d2538cf5ae62fa4aa80b"}), "42390f3972df625ea0535fd29ade7b7e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Reason do Payment deve ser \"Insufficient funds (simulated)\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "7514ae10955e625583b3ccf26afc00be"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9907dffab1157c5fb912104d5c39f974", "BDD/Features/PaymentService.feature", "Preservar OrderId no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3d4a697f2f062c5992735be32e03ea38"}), "534abe8bfaf4dc5b8304acbc932f9e1d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com OrderId específico"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b67df8ba25ce585c849bc8ec0e238aa5"}), "ef0183f77ae8eb568f775c2291c3da0d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f02ba36b9ee421538109a923c43deb03"}), "93321e96be5aef52ba8c93d7ce27a4d7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve preservar o OrderId do pedido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "08f6a4f012c17d56827f823fbd0d2c72"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1b402f94dfb5ee52996ad147860db1d8", "BDD/Features/PaymentService.feature", "Preservar UserId no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c3cbf44e936b045fa7140156a87768d0"}), "b168bd0309c1295785ba084fcb7dd823", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com UserId específico"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "635ba07de4e8ad55a4a34f03d363031c"}), "1c68c1e6dfb80a55a6db6ae46530f383", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3274491d79ceb65087513d7e7a75184c"}), "ddf17e788ee7275492d01ce6f9edeb04", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve preservar o UserId do pedido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "33e62c3727d3d1558e0a661b508464ae"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b3c7b450a4b75c5ba2f409841e709215", "BDD/Features/PaymentService.feature", "Preservar GameId no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5a3fb50f08e21553b5878914313861b4"}), "d3f5cbe15b3173589dec343e5e73ff0e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com GameId específico"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e851ff2d35cd665e9664dbb79df8fba3"}), "222d21564abfc85aa30380fbaa47e1ab", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4ebdd2155e4cf15daf8c4230ac327daa"}), "1155c8cdfc8b045d8623168e2ad96810", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve preservar o GameId do pedido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "b3af739ca46b3552b21a07439ef9be44"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("45ee0175c57cb55eb550d1c73c599a0d", "BDD/Features/PaymentService.feature", "Preservar GameTitle no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b6ce1e3de2f72c59b55b1a1b0d8d1702"}), "3af8806392872853945843979f213bb0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com GameTitle \"Elden Ring\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "27569a2e88cdd05b891393983dcfc9b9"}), "2320cf19f488995baaa365c08e966e44", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2ee7c14b49bac35fba06bd5c326b9f5d"}), "93afe5a7e06cd0539abf57c35e07f12d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter GameTitle \"Elden Ring\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "2335ed5b93b9de51989da3ec2b7a3f8b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("84b115631781355fb1ae3c99a0e5a8f7", "BDD/Features/PaymentService.feature", "Preservar UserEmail no Payment", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e40e8458ea8aa7588ed6896354be29a4"}), "bebf8bc39e0dab56926e1a90d7c7e305", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido com UserEmail \"jogador@fcg.com\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a626b6099929445fa861c676763d8903"}), "8a5b4e578cd54a50be4e98b3d26d3964", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5a3b736a821c005fa2e00dc79177d8e2"}), "53000b0bed8ead5fa04f6afc2569e2fe", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter UserEmail \"jogador@fcg.com\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "006a006119201a5fa64fd3510b38558c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6708e83e105cb45fa8f1991bcdb9ffde", "BDD/Features/PaymentService.feature", "Payment deve ter Id único", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f54778d40f517c5898bc8fc22366cf42"}), "52a5dcae4405635bb889bf19b77b63b6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 30.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5daa6ee666dc435b9778e86fde36c0d9"}), "8ed747f073f32452af3398fedcf68cb0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "988642afec457855b6e5c413b2f7cd2e"}), "c3b578fdcd38f950917206efcf2199e4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o Payment deve ter um Id não vazio")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "d147b1ea10d7e85a84b807040db8d7b2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f86c88e51e53bf55a022832a9a7c4ef5", "BDD/Features/PaymentService.feature", "Repositório deve ser chamado ao processar pagamento", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7307c48d123eed57ad62fb780295e8fd"}), "c677b98d7ab1ba53893572478bddd9b0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 45.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9d9e60731295505dbf7bda5c560583c7"}), "85e58fea9d071b589d9c89d74812ae73", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e491131a33e445c9d3245a3df30b1c3"}), "18d14c3d943a3d559d40fd1dda9a9198", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o repositório deve ter persistido o Payment exatamente uma vez")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "8bc12b31d39ff7589914347fb6bf561b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("efacd5c3c71413508535f120360670cd", "BDD/Features/PaymentService.feature", "ProcessedAt deve ser próximo do momento atual", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0adb71f88c148c5bb529b5d091ea9914"}), "2f5fd7661f764a5ea8b06be74ddd94f1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 75.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c879c9af3c4c056b7db539bc8180d13"}), "bbef4da010b12452ac35a779b3a26f56", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "17b4a4e5d412b35ca06447d753f90d8f"}), "403268fd4ad5255fa45f01e18681f5b5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "o ProcessedAt do Payment deve ser próximo do momento atual")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "b90f55266e6c9d558c2d0ab5f4b96672"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a86986efebf39c5390e41cfef6b694ab", "BDD/Features/PaymentService.feature", "Dois pagamentos devem ter Ids diferentes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c51bce16d703053ad2ffcdf24cd9e24"}), "ebd5dfc1f0a32558b786a0a5797ee16a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "dois pedidos válidos distintos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "62236919f170195bbe4e720e209e85f1"}), "19e6948bb61c2752bfdb46b9aea88154", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa ambos os pagamentos com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b7b1289b77d10552b912f01b77b5c868"}), "2015f17c1718ea5c9a977e5581256b2e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "os dois Payments devem ter Ids diferentes")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "811380c1a3bf8f58b4e12c4a08623fb7"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e90f7504c05f1f5b9717e067509796c8", "BDD/Features/PaymentService.feature", "Strategy de aprovação deve ser consultada ao processar", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e34e1b4e3ac8d55b7ad5102ae8dc888"}), "4b8d0ab800b210509a14c956687ab225", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "um pedido válido com preço de 99.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e3a13b6d9c34745d94b4f12b5ac49051"}), "5dffff4284361e5aa759955c8e3f32d7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "o serviço processa o pagamento com resultado aprovado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8b249516aa460456b468431608739ca3"}), "6ae850d2e4e61752b21070351b8ce038", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a strategy de aprovação deve ter sido consultada exatamente uma vez")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "9f6dfba3aa1a2654bce9dd6b9512fcd6"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PaymentServiceFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PaymentServiceFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PaymentServiceFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Processar pagamento aprovado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Processar pagamento aprovado")]
        public async global::System.Threading.Tasks.Task ProcessarPagamentoAprovado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Processar pagamento aprovado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("um pedido válido com preço de 59.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("o Payment deve ter status \"Approved\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("o Amount do Payment deve ser 59.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("o Reason do Payment deve ser nulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Processar pagamento rejeitado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Processar pagamento rejeitado")]
        public async global::System.Threading.Tasks.Task ProcessarPagamentoRejeitado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Processar pagamento rejeitado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("um pedido válido com preço de 120.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado rejeitado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("o Payment deve ter status \"Rejected\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.AndAsync("o Reason do Payment deve ser \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar OrderId no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar OrderId no Payment")]
        public async global::System.Threading.Tasks.Task PreservarOrderIdNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar OrderId no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("um pedido com OrderId específico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("o Payment deve preservar o OrderId do pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar UserId no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar UserId no Payment")]
        public async global::System.Threading.Tasks.Task PreservarUserIdNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar UserId no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("um pedido com UserId específico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("o Payment deve preservar o UserId do pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar GameId no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar GameId no Payment")]
        public async global::System.Threading.Tasks.Task PreservarGameIdNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar GameId no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("um pedido com GameId específico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("o Payment deve preservar o GameId do pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar GameTitle no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar GameTitle no Payment")]
        public async global::System.Threading.Tasks.Task PreservarGameTitleNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar GameTitle no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("um pedido com GameTitle \"Elden Ring\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("o Payment deve ter GameTitle \"Elden Ring\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preservar UserEmail no Payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Preservar UserEmail no Payment")]
        public async global::System.Threading.Tasks.Task PreservarUserEmailNoPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preservar UserEmail no Payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
    await testRunner.GivenAsync("um pedido com UserEmail \"jogador@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("o Payment deve ter UserEmail \"jogador@fcg.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Payment deve ter Id único")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Payment deve ter Id único")]
        public async global::System.Threading.Tasks.Task PaymentDeveTerIdUnico()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Payment deve ter Id único", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("um pedido válido com preço de 30.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("o Payment deve ter um Id não vazio", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Repositório deve ser chamado ao processar pagamento")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Repositório deve ser chamado ao processar pagamento")]
        public async global::System.Threading.Tasks.Task RepositorioDeveSerChamadoAoProcessarPagamento()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Repositório deve ser chamado ao processar pagamento", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("um pedido válido com preço de 45.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("o repositório deve ter persistido o Payment exatamente uma vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ProcessedAt deve ser próximo do momento atual")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "ProcessedAt deve ser próximo do momento atual")]
        public async global::System.Threading.Tasks.Task ProcessedAtDeveSerProximoDoMomentoAtual()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessedAt deve ser próximo do momento atual", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("um pedido válido com preço de 75.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("o ProcessedAt do Payment deve ser próximo do momento atual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Dois pagamentos devem ter Ids diferentes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Dois pagamentos devem ter Ids diferentes")]
        public async global::System.Threading.Tasks.Task DoisPagamentosDevemTerIdsDiferentes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dois pagamentos devem ter Ids diferentes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 60
    await testRunner.GivenAsync("dois pedidos válidos distintos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.WhenAsync("o serviço processa ambos os pagamentos com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
    await testRunner.ThenAsync("os dois Payments devem ter Ids diferentes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Strategy de aprovação deve ser consultada ao processar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentService")]
        [global::Xunit.TraitAttribute("Description", "Strategy de aprovação deve ser consultada ao processar")]
        public async global::System.Threading.Tasks.Task StrategyDeAprovacaoDeveSerConsultadaAoProcessar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Strategy de aprovação deve ser consultada ao processar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 64
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.GivenAsync("um pedido válido com preço de 99.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
    await testRunner.WhenAsync("o serviço processa o pagamento com resultado aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("a strategy de aprovação deve ter sido consultada exatamente uma vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PaymentServiceFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PaymentServiceFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
