apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
        - name: payments-worker
          image: fcg-payments-api:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: payments-worker-config
            - secretRef:
                name: payments-worker-secret
