apiVersion: v1
kind: Secret
metadata:
  name: payments-worker-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=fcg_payments_db;Username=fcg;Password=fcg_secret"
  RabbitMq__Password: "guest"
